image: Visual Studio 2022
stack: python 3.10

environment:
  PYTHONIOENCODING: utf-8
  PYTHONUTF8: 1

install:
  - python -m pip install --upgrade pip
  - pip install flet pyinstaller
  - pip install -r requirements.txt

build_script:
  - chcp 65001
  - flet build windows --verbose

artifacts:
  - path: build\windows\*.exe
    name: MyReminderApp_Windows